M48
; DRILL file {KiCad (7.0.0)} date Tue Jun 13 01:23:34 2023
; FORMAT={3:3/ absolute / metric / suppress trailing zeros}
; #@! TF.CreationDate,2023-06-13T01:23:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC,LZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X118316Y-07331
X124096Y-07331
T2
X1468Y-1218
T0
M30
